CREATE DATABASE QLSV
go

USE QLSV
go

CREATE TABLE SINHVIEN
(
	MSQLSV INT IDENTITY PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	MSSV NVARCHAR(100) NOT NULL,
	LOP NVARCHAR(100) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH NVARCHAR(100) NOT NULL,
	MAVUNG NVARCHAR(100) NOT NULL,
	SDT NVARCHAR(100) NOT NULL,
	EMAIL NVARCHAR(100) NOT NULL,
)
GO

UPDATE SINHVIEN SET HOTEN='4', MSSV='45' , LOP='4', NGAYSINH ='4/21/2018' , GIOITINH'Nam' , MAVUNG='+84', SDT='4', EMAIL='4'WHERE MSQLSV =10

